/* FILE: EnphaseBatchTest.cls
 * AUTHOR: Rohit Jain
 * DATE: April 26, 2012
 * PURPOSE: Test class for EnphaseBatch processes
 * MODIFICATION HISTORY:
 *
 */

@isTest
public class EnphaseBatchProcessTest {
    /*
    static testMethod void runProductionPullBatch() {
        
        Account customer = new Account ( Name = 'Test Customer' );
        insert customer;
        
        Installed_System__c sys = new Installed_System__c (
            Account__c = customer.Id,
            Enphase_ID__c = '12345'
        );
        insert sys;
                
        EnphaseBatchProductionPull batch = new EnphaseBatchProductionPull();
                
        Test.startTest();
        Id batchId = Database.executeBatch(batch, 10);
        Test.stopTest();      
        
    }

    static testMethod void runProductionAlertsPullBatch() {
        
        Account customer = new Account ( Name = 'Test Customer' );
        insert customer;
        
        Installed_System__c sys = new Installed_System__c (
            Account__c = customer.Id,
            Enphase_ID__c = '12345'
        );
        insert sys;
                
        EnphaseBatchProductionAlertsPull batch = new EnphaseBatchProductionAlertsPull();
                
        Test.startTest();
        Id batchId = Database.executeBatch(batch, 10);
        Test.stopTest();      
        
    } */
}