public with sharing class SightenAPIProduct extends SightenAPIEntity {
/*
	public SightenAPIProductData data {get;set;}
	
	public SightenAPIProduct(){}

	public static String getApiName(){
		return 'solar/product';
	}


	public class SightenAPIProductData {
		public Double deposit_usd {get;set;}
		public Boolean can_quote_ipmt {get;set;}
		public String contract_type {get;set;}
		public SightenAPIRelation participant {get;set;}
		public String payment_type {get;set;}
		public String name {get;set;}
		public Boolean can_quote_rate {get;set;}
		public String solver_uuid {get;set;}
		public Boolean can_quote_cost {get;set;}

		public SightenAPIProductData(){}
	}

	public with sharing class SightenAPIProductList extends SightenAPIEntity {
		public List<SightenAPIProductData> data {get;set;}
		
		public SightenAPIProductList(){
			data = new List<SightenAPIProductData>();
		}
	}
*/}