public with sharing class SightenAPIModule extends SightenAPIEquipment {
/*
	public SightenAPIModuleData data {get;set;}
	public SightenAPIModuleRequest request {get;set;}

	public SightenAPIModule(){
		data = new SightenAPIModuleData();
		request = new SightenAPIModuleRequest();
	}

	public override String buildRequestBody(){
		return request.toJsonString();
	}

	public static String getApiName(){
		return 'solar/module_model';
	}


	public class SightenAPIModuleData extends SightenAPIEquipment.SightenAPIEquipmentData {
		public SightenAPIModuleData(){}
	}

	public class SightenAPIModuleRequest extends SightenAPIEquipment.SightenAPIEquipmentRequest {
		public SightenAPIModuleRequest(){}
	}

	public with sharing class SightenAPIModuleList extends SightenAPIEquipment {
		public List<SightenAPIModuleData> data {get;set;}
		
		public SightenAPIModuleList(){
			data = new List<SightenAPIModuleData>();
		}
	}
*/}