public with sharing class SightenAPIUtility extends SightenAPIEntity {
/*
	public SightenAPIUtilityData data {get;set;}
	
	public SightenAPIUtility(){
		data = new SightenAPIUtilityData();
	}

	public static String getApiName(){
		return 'solar/utility';
	}


	public class SightenAPIUtilityData {
		public String natural_id {get;set;}
		public String uuid {get;set;}
		public SightenAPIRelation territories {get;set;}
		public SightenAPIRelation rate_schedules {get;set;}
		public Datetime date_created {get;set;}
		public Datetime date_updated {get;set;}

		public SightenAPIUtilityData(){}
	}


	public with sharing class SightenAPIUtilityList extends SightenAPIEntity {
		public List<SightenAPIUtilityData> data {get;set;}
		
		public SightenAPIUtilityList(){
			data = new List<SightenAPIUtilityData>();
		}
	}
*/}