public with sharing class SightenAPIProposal extends SightenAPIEntity {
/*
	public SightenAPIProposalData data {get;set;}
	
	public SightenAPIProposal(){}

	public static String getApiName(){
		return 'rest/solar_proposal';
	}


	public class SightenAPIProposalData {
		public String name {get;set;}
		public Boolean locked {get;set;}
		public String uuid {get;set;}
		public List<String> quotes {get;set;}
	}

	public with sharing class SightenAPIProposalList extends SightenAPIEntity {
		public List<SightenAPIProposalData> data {get;set;}
		
		public SightenAPIProposalList(){
			data = new List<SightenAPIProposalData>();
		}
	}
*/}