public virtual class SightenAPIEquipment extends SightenAPIEntity {
/*
	public SightenAPIEquipmentData data {get;set;}
	public SightenAPIEquipmentRequest request {get;set;}

	public SightenAPIEquipment(){
		data = new SightenAPIEquipmentData();
		request = new SightenAPIEquipmentRequest();
	}

	public override virtual String buildRequestBody(){
		return request.toJsonString();
	}

	public virtual class SightenAPIEquipmentData {
		public String natural_id {get;set;}
		public String model {get;set;}
		public Datetime date_created {get;set;}
		public Datetime date_updated {get;set;}
		public SightenAPIRelation manufacturer {get;set;}
		public String uuid {get;set;}

		public SightenAPIEquipmentData(){}
	}

	public virtual class SightenAPIEquipmentRequest extends SightenAPIEntity.SightenAPIEntityRequest {
		public SightenAPIEquipmentRequest(){}
	}

	public virtual class SightenAPIEquipmentList extends SightenAPIEntity {
		public List<SightenAPIEquipmentData> data {get;set;}
		
		public SightenAPIEquipmentList(){
			data = new List<SightenAPIEquipmentData>();
		}
	}
*/}