public with sharing class SightenAPIInverter extends SightenAPIEquipment {
/*
	public SightenAPIInverterData data {get;set;}
	public SightenAPIInverterRequest request {get;set;}

	public SightenAPIInverter(){
		data = new SightenAPIInverterData();
		request = new SightenAPIInverterRequest();
	}

	public override String buildRequestBody(){
		return request.toJsonString();
	}

	public static String getApiName(){
		return 'solar/inverter_model';
	}


	public class SightenAPIInverterData extends SightenAPIEquipment.SightenAPIEquipmentData {
		public SightenAPIInverterData(){}
	}

	public class SightenAPIInverterRequest extends SightenAPIEquipment.SightenAPIEquipmentRequest {
		public SightenAPIInverterRequest(){}
	}

	public with sharing class SightenAPIInverterList extends SightenAPIEquipment {
		public List<SightenAPIInverterData> data {get;set;}
		
		public SightenAPIInverterList(){
			data = new List<SightenAPIInverterData>();
		}
	}
*/}